import type { NavigationSections } from "@/types/navigation";

export const navigationSections: NavigationSections = [
    {
        title: "Getting Started",
        items: [
            { name: "Introduction", href: "/docs" },
            { name: "Installation", href: "/docs/installation" },
        ],
    },
    {
        title: "Components",
        items: [
            { name: "Overview", href: "/docs/components" },
            { name: "Accordion", href: "/docs/components/accordion" },
            { name: "Alert", href: "/docs/components/alert" },
            { name: "Avatar", href: "/docs/components/avatar" },
            { name: "Badge", href: "/docs/components/badge" },
            { name: "Breadcrumbs", href: "/docs/components/breadcrumbs" },
            { name: "Button", href: "/docs/components/button" },
            { name: "Calendar", href: "/docs/components/calendar" },
            { name: "Card", href: "/docs/components/card" },
            { name: "Checkbox", href: "/docs/components/checkbox" },
            { name: "Checkbox Group", href: "/docs/components/checkbox-group" },
            { name: "Chip", href: "/docs/components/chip" },
            { name: "Color picker", href: "/docs/components/color-picker" },
            { name: "Date picker", href: "/docs/components/date-picker" },
            { name: "Drawer", href: "/docs/components/drawer" },
            { name: "Dropdown", href: "/docs/components/dropdown" },
            { name: "Form", href: "/docs/components/form" },
            { name: "Grid", href: "/docs/components/grid" },
            { name: "Icon", href: "/docs/components/icon" },
            { name: "Image", href: "/docs/components/image" },
            { name: "Link", href: "/docs/components/link" },
            { name: "Listbox", href: "/docs/components/listbox" },
            { name: "Menu button", href: "/docs/components/menu-button" },
            { name: "Messages", href: "/docs/components/messages" },
            { name: "Modal", href: "/docs/components/modal" },
            { name: "Pagination", href: "/docs/components/pagination" },
            { name: "Progress", href: "/docs/components/progress" },
            { name: "Radio", href: "/docs/components/radio" },
            { name: "Radio Group", href: "/docs/components/radio-group" },
            { name: "Ripple", href: "/docs/components/ripple" },
            { name: "Select", href: "/docs/components/select" },
            { name: "Slider", href: "/docs/components/slider" },
            { name: "Switch", href: "/docs/components/switch" },
            { name: "Table", href: "/docs/components/table" },
            { name: "Tabs", href: "/docs/components/tabs" },
            { name: "Text nowrap", href: "/docs/components/text-nowrap" },
            { name: "Textarea", href: "/docs/components/textarea" },
            { name: "Textfield", href: "/docs/components/textfield" },
            { name: "Typography", href: "/docs/components/typography" },
        ],
    },
    {
        title: "Theming",
        items: [
            { name: "Overview", href: "/docs/themes" },
            { name: "Theme Component", href: "/docs/themes/theme-component" },
            { name: "Colors", href: "/docs/themes/colors" },
            { name: "Typography", href: "/docs/themes/typography" },
            { name: "Dark Mode", href: "/docs/themes/dark-mode" },
            { name: "Customization", href: "/docs/themes/customization" },
        ],
    },
    {
        title: "Examples",
        items: [
            { name: "Basic Usage", href: "/docs/examples" },
            { name: "Forms", href: "/docs/examples/forms" },
            { name: "Data Display", href: "/docs/examples/data-display" },
            { name: "Layouts", href: "/docs/examples/layouts" },
            { name: "Integrations", href: "/docs/examples/integrations" },
        ],
    },
    {
        title: "Advanced",
        items: [
            { name: "Accessibility", href: "/docs/accessibility" },
            { name: "Performance", href: "/docs/performance" },
            { name: "Testing", href: "/docs/testing" },
            { name: "Migration", href: "/docs/migration" },
        ],
    },
];
